# Generated by Django 5.0.1 on 2024-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200, unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('employee_image', models.ImageField(blank=True, default='default.jpg', upload_to='images')),
                ('address', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200, null=True)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
    ]
