# Generated by Django 5.0.1 on 2024-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_remove_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
