# Generated by Django 5.0.1 on 2024-02-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_alter_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skill',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
