# Generated by Django 5.0.1 on 2024-02-17 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_rename_skill_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(max_length=200),
        ),
    ]
